'use strict';
(() => {
  const G=window.GatduellApp,{C,B,$,S,escapeHtml,premium,locked,open,close,store,loadCity,cityUI}=G;
  function renderCities(){
    const all=C.all();
    if($('cityPreviewGrid'))$('cityPreviewGrid').innerHTML=all.map(c=>`<article class="city-preview-card ${c.premium?'premium':''}"><div><small>${c.region}</small><strong>${c.name}</strong><span>${c.premium?'Premiumstad':'Ingår gratis'}</span></div><b class="city-tier">${locked(c)?'🔒 PREMIUM':c.premium?'✓ PREMIUM':'FREE'}</b></article>`).join('');
    if($('cityCatalogGrid'))$('cityCatalogGrid').innerHTML=all.map(c=>`<article class="city-catalog-card ${S.city.slug===c.slug?'active':''} ${locked(c)?'locked':''}"><small>${c.premium?'PREMIUM CITY':'INCLUDED'}</small><h3>${c.name}</h3><p>${c.premium?'Premiumstad · dynamiskt gatunät från OpenStreetMap.':'Ingår gratis · öppna vägdata från Umeå.'}</p><button type="button" data-city="${c.slug}">${S.city.slug===c.slug?'Vald':locked(c)?'Lås upp Premium':'Välj stad'}</button></article>`).join('');
    if($('citySelect')){$('citySelect').innerHTML=all.map(c=>`<option value="${c.slug}" ${locked(c)?'disabled':''}>${c.premium?'⭐ ':''}${c.name}${locked(c)?' · Premium':''}</option>`).join('');$('citySelect').value=S.city.slug}
    if($('rankingCitySelect')){$('rankingCitySelect').innerHTML=all.map(c=>`<option value="${c.slug}">${c.name}</option>`).join('');$('rankingCitySelect').value=S.city.slug}cityUI();
  }
  async function chooseCity(slug,shouldClose=true){
    const c=C.get(slug);S.requested=c.slug;if(locked(c)){$('cityCatalogMessage')&&($('cityCatalogMessage').textContent=`${c.name} ingår i Premium.`);open('accountModal');return false}
    S.city=c;store.set('city',c.slug);renderCities();const ok=await loadCity(c);if(ok&&shouldClose)close('citiesModal');return ok;
  }
  function localStats(){try{return JSON.parse(localStorage.getItem('umea-gatduell:matchStats')||'{}')||{}}catch{return{}}}
  function renderLocal(){const rows=$('leaderboardRows'),empty=$('leaderboardEmpty');if(!rows||!empty)return;const list=Object.values(localStats()).map(x=>({...x,wins:+x.wins||0,matches:+x.matches||0})).sort((a,b)=>b.wins-a.wins||(b.wins/Math.max(1,b.matches))-(a.wins/Math.max(1,a.matches))).slice(0,8);rows.innerHTML=list.map((x,i)=>`<div class="leaderboard-row"><div class="leaderboard-name"><span class="leaderboard-rank">${i+1}</span><strong>${escapeHtml(x.name)}</strong></div><span class="leaderboard-value">${x.wins}</span><span class="leaderboard-value">${x.matches}</span><span class="leaderboard-value">${x.matches?Math.round(x.wins/x.matches*100):0}%</span></div>`).join('');empty.classList.toggle('hidden',!!list.length)}
  function recordLocal(winner){if(!S.state||S.state.recorded)return;S.state.recorded=true;const s=localStats();S.state.players.forEach(p=>{const k=p.name.trim().toLocaleLowerCase('sv-SE'),x=s[k]||{name:p.name,wins:0,matches:0,lastPlayed:0};x.name=p.name;x.matches++;x.lastPlayed=Date.now();if(p===winner)x.wins++;s[k]=x});try{localStorage.setItem('umea-gatduell:matchStats',JSON.stringify(s))}catch{}renderLocal();void recordOnline(winner)}
  async function recordOnline(winner){if(!B?.isConfigured?.()||!S.session||!S.profile||!S.state)return;try{await B.recordMatch({citySlug:S.state.citySlug,won:winner===S.state.players[0],playerScore:S.state.players[0].score,opponentScore:S.state.players[1].score,difficulty:S.state.difficulty,opponentName:S.state.players[1].name})}catch(e){console.warn(e)}}
  async function refreshAuth(restore=false){
    if(!B?.isConfigured?.()){S.session=S.profile=null;accountUI();renderCities();return}
    try{S.session=await B.session();S.profile=S.session?await B.profile(true):null}catch{S.session=S.profile=null}accountUI();renderCities();if(restore&&premium()){const c=C.get(S.requested);if(c.premium&&c.slug!==S.city.slug)await chooseCity(c.slug,false)}
  }
  function accountUI(){const signed=!!S.session?.user&&!!S.profile;$('backendStatusText')&&($('backendStatusText').textContent=B?.isConfigured?.()?'Kontot kopplar vinster till global ranking och premiumåtkomst.':'Online-lagret är installerat men Supabase är inte konfigurerat ännu. Spelet fungerar i gästläge.');$('accountSignedOut')?.classList.toggle('hidden',signed);$('accountSignedIn')?.classList.toggle('hidden',!signed);$('accountBtn')&&($('accountBtn').textContent=signed?(premium()?'Premium':'Konto'):'Konto');$('setupAccountState')&&($('setupAccountState').textContent=signed?S.profile.display_name:'Gästläge');if(signed){$('accountProfileName').textContent=S.profile.display_name;$('accountProfileEmail').textContent=S.session.user.email||'';$('accountPremiumBadge').textContent=premium()?'PREMIUM':'FREE';$('accountPremiumBadge').classList.toggle('active',premium());$('premiumBtn').classList.toggle('hidden',premium());if(store.get('name1','Spelare 1')==='Spelare 1')$('name1').value=S.profile.display_name}cityUI()}
  const msg=(t='',k='')=>{const e=$('accountMessage');if(e){e.textContent=t;e.className=`account-message${k?` ${k}`:''}`}};
  async function signIn(){const email=$('accountEmail').value.trim(),pw=$('accountPassword').value;if(!email||!pw)return msg('Fyll i e-post och lösenord.','bad');msg('Loggar in…');try{await B.signIn(email,pw);await refreshAuth(true);msg('Inloggad. Global ranking är aktiv.','good')}catch(e){msg(e.message||'Kunde inte logga in.','bad')}}
  async function signUp(){const email=$('accountEmail').value.trim(),pw=$('accountPassword').value,name=$('accountDisplayName').value.trim()||email.split('@')[0];if(!email||pw.length<6)return msg('Ange giltig e-post och minst 6 tecken i lösenordet.','bad');msg('Skapar konto…');try{const r=await B.signUp(email,pw,name);await refreshAuth();msg(r?.session?'Kontot är klart.':'Kontot är skapat. Bekräfta e-posten och logga sedan in.','good')}catch(e){msg(e.message||'Kunde inte skapa konto.','bad')}}
  async function signOut(){try{await B.signOut();S.session=S.profile=null;if(S.city.premium)await chooseCity('umea',false);accountUI();renderCities();msg('Utloggad.','good')}catch(e){msg(e.message||'Kunde inte logga ut.','bad')}}
  function buyPremium(){if(B?.premiumCheckoutUrl){location.href=B.premiumCheckoutUrl;return}msg('Premiumflödet är förberett. Lägg checkout-länken i config.js för att aktivera betalning.','bad')}
  async function globalRanking(){const status=$('globalRankingStatus'),rows=$('globalRankingRows'),slug=$('rankingCitySelect')?.value||S.city.slug;if(!B?.isConfigured?.()){status.textContent='Global ranking aktiveras när Supabase är konfigurerat.';status.className='global-ranking-status';rows.innerHTML='';return}status.textContent='Hämtar ranking…';try{const list=await B.globalLeaderboard(slug,50);rows.innerHTML=list.map((x,i)=>`<div class="global-ranking-row"><span class="rank">${i+1}</span><strong>${escapeHtml(x.name)}</strong><span class="pts">${x.points}</span><span>${x.wins}</span><span>${x.matches}</span></div>`).join('');status.textContent=list.length?'':'Ingen ranking ännu.';status.className='global-ranking-status'}catch(e){status.textContent=e.message||'Kunde inte hämta ranking.';status.className='global-ranking-status bad'}}
  G.online={renderCities,chooseCity,renderLocal,recordLocal,refreshAuth,accountUI,msg,signIn,signUp,signOut,buyPremium,globalRanking};
})();
