'use strict';
(() => {
  const G=window.GatduellApp,{E,C,B,$,S,TARGET,store,level,open,close,live,setMapExplore,restore}=G,O=G.online;
  function start(){if(!S.graph)return;if(G.locked(S.city)){open('accountModal');return}const n1=$('name1').value.trim()||'Spelare 1',n2=$('name2').value.trim()||'Spelare 2',difficulty=$('difficultySelect').value,turnSeconds=Math.max(0,+$('timerSelect').value||0);store.set('name1',n1);store.set('name2',n2);store.set('difficulty',difficulty);store.set('timer',turnSeconds);store.set('city',S.city.slug);S.state={players:[{name:n1,score:0},{name:n2,score:0}],difficulty,turnSeconds,citySlug:S.city.slug,round:1,turn:0,current:null,used:[],running:true,recorded:false};live(true);close('modal');round()}
  function round(){stopTimer();S.state.current=E.chooseStart(S.graph);S.state.used=[S.state.current];S.state.turn=(S.state.round-1)%2;S.state.running=true;setMessage('Skriv en gata som uppfyller reglerna.');$('pathHint').classList.add('hidden');render();turn()}
  function turn(){if(!S.state?.running)return;const legal=E.reachableUnused(S.graph,S.state.current,S.state.used,level().steps);if(!legal.length){const w=S.state.players[S.state.turn?0:1];w.score++;return finish(`${S.state.players[S.state.turn].name} har ingen möjlig gata kvar. ${w.name} vinner rundan.`)}$('streetInput').value='';$('suggestions').innerHTML='';$('streetInput').disabled=false;$('submitBtn').disabled=false;$('prompt').textContent=`${S.state.players[S.state.turn].name}: vilken gata ligger rätt från ${S.state.current}?`;setMessage('Skriv ett gatunamn. Förslagen visar bara namn – inte om svaret är rätt.');players();startTimer();setTimeout(()=>$('streetInput').focus({preventScroll:true}),40)}
  function answer(){if(!S.state?.running)return;const raw=$('streetInput').value.trim();if(!raw)return;stopTimer();const r=E.validateMove(S.graph,S.state.current,raw,S.state.used,level().steps);if(!r.ok){const w=S.state.players[S.state.turn?0:1];w.score++;let why='Svaret är inte giltigt.';if(r.reason==='unknown')why=`${raw} finns inte i gatunätet.`;if(r.reason==='used')why=`${r.name} har redan använts.`;if(r.reason==='not-crossing')why=level().steps===1?`${r.name||raw} ansluter inte direkt till ${S.state.current}.`:`${r.name||raw} ligger inte inom ${level().steps} steg från ${S.state.current}.`;return finish(`${why} ${w.name} vinner rundan.`,true)}S.state.current=r.name;S.state.used.push(r.name);if(r.steps>1){$('pathHint').textContent=`✓ ${r.steps} steg: ${r.path.join(' → ')}`;$('pathHint').classList.remove('hidden')}else $('pathHint').classList.add('hidden');setMessage(`Rätt! ${r.name}.`,'good');S.state.turn=S.state.turn?0:1;render();setTimeout(turn,650)}
  function startTimer(){stopTimer();const s=S.state.turnSeconds;if(!s){$('timerTrack').style.display='none';$('timerText').textContent='Ingen tidsgräns';return}$('timerTrack').style.display='block';const end=performance.now()+s*1000,tick=()=>{const left=Math.max(0,end-performance.now());$('timerText').textContent=`${Math.ceil(left/1000)} sek`;$('timerBar').style.width=`${left/(s*1000)*100}%`;if(left<=0){stopTimer();const w=S.state.players[S.state.turn?0:1];w.score++;finish(`Tiden tog slut. ${w.name} vinner rundan.`,true)}};tick();S.timer=setInterval(tick,100)}
  function stopTimer(){if(S.timer){clearInterval(S.timer);S.timer=null}}
  function finish(text,bad=false){stopTimer();S.state.running=false;$('streetInput').disabled=true;$('submitBtn').disabled=true;$('suggestions').innerHTML='';setMessage(text,bad?'bad':'good');render();const champ=S.state.players.find(p=>p.score>=TARGET);if(champ){O.recordLocal(champ);S.lastShare=sharePayload(champ);setTimeout(()=>showResult(`${champ.name} vinner matchen!`,`${S.state.players[0].name} ${S.state.players[0].score}–${S.state.players[1].score} ${S.state.players[1].name}`,'Spela igen',S.lastShare),850)}else setTimeout(()=>showResult('Rundan är avgjord',text,'Nästa runda'),850)}
  function sharePayload(w){const l=S.state.players.find(p=>p!==w),score=`${S.state.players[0].score}–${S.state.players[1].score}`;return{title:`Gatduell ${S.city.name}`,text:`🏙️ ${w.name} vann Gatduell ${S.city.name} ${score} mot ${l?.name||'motståndaren'} · ${level().label}. Kan du slå det?`,url:location.href.split('#')[0].split('?')[0],winner:w.name,score,meta:`${S.city.name} · ${level().label} · ${S.state.turnSeconds?`${S.state.turnSeconds} sek/tur`:'utan tidsgräns'}`}}
  async function share(){if(!S.lastShare)return;try{if(navigator.share)await navigator.share({title:S.lastShare.title,text:S.lastShare.text,url:S.lastShare.url});else await navigator.clipboard.writeText(`${S.lastShare.text} ${S.lastShare.url}`)}catch{}}
  function showResult(title,text,button,data=null){S.modalMode=button==='Spela igen'?'restart':'next';$('modalTitle').textContent=title;$('modalText').textContent=text;$('setupFields').classList.add('hidden');$('loadStatus').classList.add('hidden');$('modalPrimary').disabled=false;$('modalPrimary').textContent=button;if(data){$('resultWinner').textContent=`${data.winner} tar segern`;$('resultScore').textContent=data.score;$('resultMeta').textContent=data.meta;$('resultCard').classList.remove('hidden');$('shareResultBtn').classList.remove('hidden')}else{$('resultCard').classList.add('hidden');$('shareResultBtn').classList.add('hidden')}open('modal')}
  function setup(){stopTimer();S.modalMode='setup';live(false);$('modalTitle').textContent='Starta match';$('modalText').textContent=`Ni turas om att skriva gator i ${S.city.name}. Fel svar förlorar rundan. Först till tre rundvinster vinner.`;$('setupFields').classList.remove('hidden');$('loadStatus').classList.remove('hidden');$('resultCard').classList.add('hidden');$('shareResultBtn').classList.add('hidden');S.lastShare=null;$('modalPrimary').textContent=S.graph?'Starta match':`Laddar ${S.city.name}…`;$('modalPrimary').disabled=!S.graph;open('modal')}
  function modalPrimary(){if(S.modalMode==='setup')return start();if(S.modalMode==='next'){close('modal');S.state.round++;return round()}if(S.modalMode==='restart')setup()}
  function setMessage(t,k=''){const e=$('message');e.textContent=t;e.className=`message${k?` ${k}`:''}`}
  function render(){if(!S.state)return;players();$('roundNo').textContent=S.state.round;$('currentStreet').textContent=S.state.current||'—';$('chain').innerHTML=S.state.used.slice(-10).map(n=>`<span>${G.escapeHtml(n)}</span>`).join('');const lv=level();$('difficultyBadge').textContent=`${lv.icon} ${lv.label} · ${lv.help}`;$('rulesText').textContent=S.state.turnSeconds?'Fel anslutning, återanvänd gata eller slut på tiden förlorar rundan. Först till tre vinner.':'Fel anslutning eller återanvänd gata förlorar rundan. Först till tre vinner.';drawStreetHistory()}
  function players(){$('player1Name').textContent=S.state.players[0].name;$('player2Name').textContent=S.state.players[1].name;$('player1Score').textContent=S.state.players[0].score;$('player2Score').textContent=S.state.players[1].score;$('player1Card').classList.toggle('active',S.state.running&&S.state.turn===0);$('player2Card').classList.toggle('active',S.state.running&&S.state.turn===1);$('turnLabel').textContent=S.state.running?`${S.state.players[S.state.turn].name} spelar`:'Rundan avgjord'}

  function streetPolylines(name,style){
    const street=S.graph?.get(name);
    if(!street?.lines?.length)return[];
    return street.lines.map(line=>L.polyline(line.map(([lon,lat])=>[lat,lon]),{interactive:false,lineCap:'round',lineJoin:'round',...style}));
  }

  function drawStreetHistory(){
    if(!S.map||!S.graph||!S.state)return;
    if(S.usedLayer){S.usedLayer.remove();S.usedLayer=null}
    if(S.highlight){S.highlight.remove();S.highlight=null}
    const used=S.state.used||[];
    const previous=used.slice(0,-1);
    const historyLayers=previous.flatMap(name=>streetPolylines(name,{color:'#10a99a',weight:5,opacity:.58}));
    if(historyLayers.length)S.usedLayer=L.featureGroup(historyLayers).addTo(S.map);
    const current=used.at(-1);
    if(!current)return;
    const halo=streetPolylines(current,{color:'#ffffff',weight:11,opacity:.9});
    const active=streetPolylines(current,{color:'#ff9f1c',weight:7,opacity:.98});
    const layers=[...halo,...active];
    if(layers.length)S.highlight=L.featureGroup(layers).addTo(S.map);
  }

  function suggestions(){if(!S.graph||!S.state?.running)return $('suggestions').innerHTML='';const v=$('streetInput').value;if(v.trim().length<2)return $('suggestions').innerHTML='';$('suggestions').innerHTML=E.suggestions(S.graph,v,7).map(n=>`<button type="button" data-name="${G.escapeHtml(n)}">${G.escapeHtml(n)}</button>`).join('')}
  function bind(){
    $('answerForm').addEventListener('submit',e=>{e.preventDefault();answer()});$('streetInput').addEventListener('input',suggestions);$('suggestions').addEventListener('click',e=>{const b=e.target.closest('button[data-name]');if(b){$('streetInput').value=b.dataset.name;$('suggestions').innerHTML='';$('streetInput').focus()}});$('modalPrimary').addEventListener('click',modalPrimary);$('newGameBtn').addEventListener('click',setup);$('heroStartBtn')?.addEventListener('click',setup);$('heroHowBtn')?.addEventListener('click',()=>$('howItWorks')?.scrollIntoView({behavior:'smooth'}));$('mapModeBtn')?.addEventListener('click',()=>setMapExplore(!S.mapExplore));$('shareResultBtn')?.addEventListener('click',share);
    const cities=()=>{O.renderCities();open('citiesModal')};$('cityCatalogBtn')?.addEventListener('click',cities);$('cityCatalogCta')?.addEventListener('click',cities);$('cityCatalogGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-city]');if(b)void O.chooseCity(b.dataset.city)});$('citySelect')?.addEventListener('change',e=>void O.chooseCity(e.target.value,false));
    const ranking=()=>{open('rankingModal');void O.globalRanking()};$('rankingBtn')?.addEventListener('click',ranking);$('globalRankingCta')?.addEventListener('click',ranking);$('rankingCitySelect')?.addEventListener('change',O.globalRanking);$('refreshRankingBtn')?.addEventListener('click',O.globalRanking);
    $('accountBtn')?.addEventListener('click',()=>{O.msg();open('accountModal')});$('signInBtn')?.addEventListener('click',O.signIn);$('signUpBtn')?.addEventListener('click',O.signUp);$('signOutBtn')?.addEventListener('click',O.signOut);$('premiumBtn')?.addEventListener('click',O.buyPremium);document.addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(b)close(b.dataset.close)});
  }
  async function boot(){live(false);O.renderLocal();O.renderCities();restore();G.initMap();bind();if(B?.subscribe)B.subscribe(()=>void O.refreshAuth());await O.refreshAuth();const wanted=C.get(S.requested);S.city=!wanted.premium||G.premium()?wanted:C.get('umea');O.renderCities();await G.loadCity(S.city)}
  void boot();
})();
